name: Publish Chmod Page

on:
  push:
    branches: [ main, gh-pages ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Project - Node.js ${{ matrix.node-version }}
      run: |
        npm install
        npm run build
    - name: Deploy Project
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        base_href: /chmodchamp/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/chmodchamp